FROM alpine:latest

ARG MIGRATE_VERSION=4.19.1

RUN apk add --no-cache curl \
    && curl -L \
       "https://github.com/golang-migrate/migrate/releases/download/v${MIGRATE_VERSION}/migrate.linux-amd64.tar.gz" \
       -o /tmp/migrate.tar.gz \
    && tar -xzf /tmp/migrate.tar.gz -C /usr/local/bin \
    && rm /tmp/migrate.tar.gz

WORKDIR /app

ENTRYPOINT ["migrate"]
